ktor:
  application:
    modules:
      - com.milko.ApplicationKt.module
  deployment:
    port: 8080
  database:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/student"
    user: "student"
    password: "student"
